name: Auto Build for Docker image

on:
  push:
    # Pattern matched against refs/tags
    tags:
      - '**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          build-args: |
            AWS_BASE_VERSION=v0.3.9
          tags: |
            vipcube/dockercli-with-aws-k8s-helm:latest
            vipcube/dockercli-with-aws-k8s-helm:${{ github.ref_name }}
